# Generated by Django 4.2.6 on 2025-02-28 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='licence_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 20, 32, 50, 564495)),
        ),
    ]
